"""Permitir producto_id nulo y ON DELETE SET NULL en DetalleVenta

Revision ID: 704e72267fb8
Revises: f814497188c7
Create Date: 2025-09-30 22:09:46.618141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '704e72267fb8'
down_revision = 'f814497188c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_venta', schema=None) as batch_op:
        batch_op.alter_column('producto_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('detalle_venta_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'productos', ['producto_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_venta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detalle_venta_ibfk_1'), 'productos', ['producto_id'], ['id'])
        batch_op.alter_column('producto_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
