"""Ajustar FK de cliente con ON DELETE SET NULL

Revision ID: bb155636271f
Revises: 02eedcd8c7e7
Create Date: 2025-09-22 21:10:35.723160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb155636271f'
down_revision = '02eedcd8c7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistencia', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('asistencia_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cliente', ['cliente_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('servicio_cliente', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('servicio_cliente_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cliente', ['cliente_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio_cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('servicio_cliente_ibfk_1'), 'cliente', ['cliente_id'], ['id'])
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('asistencia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('asistencia_ibfk_1'), 'cliente', ['cliente_id'], ['id'])
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
