"""Añadir tabla de historial de mensajes

Revision ID: f374a34f9a75
Revises: 704e72267fb8
Create Date: 2025-10-02 01:20:40.442758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f374a34f9a75'
down_revision = '704e72267fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensajes_masivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=False),
    sa.Column('asunto', sa.String(length=150), nullable=False),
    sa.Column('cuerpo_resumen', sa.String(length=300), nullable=False),
    sa.Column('destinatario_filtro', sa.String(length=50), nullable=False),
    sa.Column('total_enviados', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensajes_masivos')
    # ### end Alembic commands ###
