"""Ajustar FK de cliente con ON DELETE SET NULL

Revision ID: f814497188c7
Revises: bb155636271f
Create Date: 2025-09-29 19:32:50.449155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f814497188c7'
down_revision = 'bb155636271f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuadre_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('ventas_efectivo_sistema', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ventas_tarjeta_sistema', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ventas_total_sistema', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_contado_efectivo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('diferencia', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servicio_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pago', sa.String(length=50), nullable=False))

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pago', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('metodo_pago')

    with op.batch_alter_table('servicio_cliente', schema=None) as batch_op:
        batch_op.drop_column('metodo_pago')

    op.drop_table('cuadre_caja')
    # ### end Alembic commands ###
