"""Añadir campo de sexo al cliente

Revision ID: fb26195a1bc7
Revises: 7bbd7e215a9a
Create Date: 2025-09-20 18:53:25.045171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb26195a1bc7'
down_revision = '7bbd7e215a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('sexo')

    # ### end Alembic commands ###
